export enum BillingProduct {
  QUICK_REVIEW = 'QUICK_REVIEW',
  QUICK_MENU = 'QUICK_MENU',
  QUICK_CONNECT = 'QUICK_CONNECT',
  QUICK_DESIGN = 'QUICK_DESIGN',
  QUICK_SCAN = 'QUICK_SCAN',
  QUICK_CRM = 'QUICK_CRM',
}
